site_name: Guía picoCTF - Ciberseguridad CIC
# site_url: https://lpumogo22.github.io/upiicsa-linux/
theme:
  name: material
  logo: assets/picoctf.png
  favicon: assets/picoctf.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: yellow
      accent: yellow 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: yellow
      accent: yellow

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xNJ7xpZj
    - icon: fontawesome/brands/github-alt
      link: https://github.com/LPUMOGO22      
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mora-gómez-luis-enrique-5a7411221/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/LPUMOGO22"  target="_blank" rel="noopener">Luis Enrique Mora Gómez</a>